site_name: The Library
site_description: "May you find your book in this place."
site_url: https://public-archive-docs.github.io/revision_archive/

markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

theme:
  name: material

  logo: assets/images/he_will_be_baked_soon.png
  favicon: assets/images/he_will_be_baked_soon.png

  font:
    text: Jura
    code: Jura

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - navigation.top

  palette:
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: lights on

    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/lightbulb
        name: lights off

nav:
  - Home: index.md

  - English:
    - Literature:
      - Overview: english/literature/index.md
      - Paper 1:
        - Romeo & Juliet:
          - Overview: english/literature/romeo_and_juliet/index.md
          - Timeline: english/literature/romeo_and_juliet/timeline.md
          - Key Themes: english/literature/romeo_and_juliet/key_themes.md
          - Trivial Stuff:
            - Relations: english/literature/romeo_and_juliet/trivial_stuff/relations.md
            - Kill Feed: english/literature/romeo_and_juliet/trivial_stuff/who_kills_who.md
        - Jekyll & Hyde:
          - Overview: english/literature/jekyll_and_hyde/index.md
          - Timeline: english/literature/jekyll_and_hyde/timeline.md
          - Key Themes: english/literature/jekyll_and_hyde/key_themes.md
          - Quotes:
            - Utterson's Quotes: english/literature/jekyll_and_hyde/quotes/utterson.md
            - Jekyll's Quotes: english/literature/jekyll_and_hyde/quotes/jekyll.md
            - Hyde's Quotes: english/literature/jekyll_and_hyde/quotes/hyde.md
            - Lanyon's Quotes: english/literature/jekyll_and_hyde/quotes/lanyon.md
            - Setting Quotes: english/literature/jekyll_and_hyde/quotes/setting.md
            - Poole's Quotes: english/literature/jekyll_and_hyde/quotes/poole.md
    - Language:
      - Overview: english/language/index.md

  - Maths:
    - Overview: maths/index.md

  - Sciences (Triple):
    - Biology:
      - Overview: sciences/biology/index.md
      - Exchange and Transport:
        - Overview: sciences/biology/exchange_and_transport/index.md
      - Coordination, Control and Homeostasis:
        - Overview: sciences/biology/coordination_control_homeostasis/index.md
      - Plant Structures and Functions:
        - Overview: sciences/biology/plant_structures_and_functions/index.md
      - Key Concepts:
        - Overview: sciences/biology/key_concepts/index.md

    - Chemistry:
      - Overview: sciences/chemistry/index.md
      - Formulae, Equations and Hazards:
        - Overview: sciences/chemistry/formulae_equations_hazards/index.md
      - Bonding:
        - Overview: sciences/chemistry/bonding/index.md
        - Forming Ions: sciences/chemistry/bonding/forming_ions.md
        - Ionic Formulae: sciences/chemistry/bonding/ionic_formulae.md
        - Ionic Bonding: sciences/chemistry/bonding/ionic_bonding.md
        - Ionic Properties: sciences/chemistry/bonding/ionic_properties.md
        - Metallic Bonding: sciences/chemistry/bonding/metallic_bonding.md
        - Covalent Bonding: sciences/chemistry/bonding/covalent_bonding.md
        - Covalent Properties: sciences/chemistry/bonding/covalent_properties.md
        - Allotropes Of Carbon: sciences/chemistry/bonding/allotropes_of_carbon.md
      - Groups in the Periodic Table:
        - Overview: sciences/chemistry/groups_in_the_periodic_table/index.md
        - The Periodic Table: sciences/chemistry/groups_in_the_periodic_table/periodic_table.md
        - Group 1: sciences/chemistry/groups_in_the_periodic_table/group_one.md
        - Explaing Trends in Group 1: sciences/chemistry/groups_in_the_periodic_table/explaining_trends_in_group_one.md
        - Group 7: sciences/chemistry/groups_in_the_periodic_table/group_seven.md
        - Reactions of Halogens: sciences/chemistry/groups_in_the_periodic_table/reactions_of_halogens.md
        - Explaining Displacement: sciences/chemistry/groups_in_the_periodic_table/explaining_displacement.md
        - Noble Gases: sciences/chemistry/groups_in_the_periodic_table/noble_gases.md
      - Reactions of Acids:
        - Overview: sciences/chemistry/reactions_of_acids/index.md
        - Acids: sciences/chemistry/reactions_of_acids/acids.md
        - Solubility Rules: sciences/chemistry/reactions_of_acids/solubility_rules.md
        - Preparing Insoluble Salts: sciences/chemistry/reactions_of_acids/preparing_insoluble_salts.md
        - Making Soluble Salts using a Insoluble Base: sciences/chemistry/reactions_of_acids/making_soluble_salts_using_unsoluble_base.md
        - Using Titration: sciences/chemistry/reactions_of_acids/using_titration.md
        - Investigating Change in pH: sciences/chemistry/reactions_of_acids/investigating_change_in_ph.md
      - Obtaining and Using Metals:
        - Overview: sciences/chemistry/obtaining_and_using_metals/index.md
        - Reactivity Series of Metals: sciences/chemistry/obtaining_and_using_metals/reactivity_series_of_metals.md
        - Displacement of Metals: sciences/chemistry/obtaining_and_using_metals/displacement_of_metals.md
        - REDOX: sciences/chemistry/obtaining_and_using_metals/redox.md
        - Extraction of Copper: sciences/chemistry/obtaining_and_using_metals/extraction_of_copper.md
        - Alternative Metal Extraction: sciences/chemistry/obtaining_and_using_metals/alternative_metal_extraction.md
        - Corrosion: sciences/chemistry/obtaining_and_using_metals/corrosion.md
        - Recycling and Life Cycle Assesment: sciences/chemistry/obtaining_and_using_metals/recycling_and_life_cycle_assesment.md
        - Transition Metals: sciences/chemistry/obtaining_and_using_metals/transition_metals.md
        - Alloys: sciences/chemistry/obtaining_and_using_metals/alloys.md
      - Energy in Reactions:
        - Overview: sciences/chemistry/energy_in_reactions/index.md
        - Exothermic Reactions: sciences/chemistry/energy_in_reactions/exothermic_reactions.md
        - Endothermic Reactions: sciences/chemistry/energy_in_reactions/endothermic_reactions.md
        - Breaking and Making Bonds: sciences/chemistry/energy_in_reactions/breaking_making_bonds.md
        - Energy Calculations: sciences/chemistry/energy_in_reactions/energy_calculations.md
      - Reversible Reactions and Equilibrium:
        - Overview: sciences/chemistry/reversible_reactions_and_equilibrium/index.md
        - Reversible Reactions: sciences/chemistry/reversible_reactions_and_equilibrium/reversible_reactions.md
        - Dynamic Equilibrium: sciences/chemistry/reversible_reactions_and_equilibrium/dynamic_equilibrium.md
        - Changing Conditions: sciences/chemistry/reversible_reactions_and_equilibrium/changing_conditions.md
        - Haber Process: sciences/chemistry/reversible_reactions_and_equilibrium/haber_process.md
        - Fertilisers and Making Ammonium Salts: sciences/chemistry/reversible_reactions_and_equilibrium/fertilisers_and_making_ammonium_salts.md
        - Making Ammonia in the Lab: sciences/chemistry/reversible_reactions_and_equilibrium/making_ammonia_in_lab.md
      - Electrolysis:
        - Overview: sciences/chemistry/electrolysis/index.md

    - Physics:
      - Overview: sciences/physics/index.md
      - Energy and Efficiency:
        - Overview: sciences/physics/energy_and_efficiency/index.md
      - Electrical Circuits:
        - Overview: sciences/physics/electrical_circuits/index.md
      - Forces and Movement:
        - Overview: sciences/physics/forces_and_movement/index.md
      - Using Electromagnetic Waves:
        - Overview: sciences/physics/using_electromagnetic_waves/index.md
      - Radioactivity:
        - Overview: sciences/physics/radioactivity/index.md
      - Astronomy:
        - Overview: sciences/physics/astronomy/index.md
      - Forces and Work Done:
        - Overview: sciences/physics/forces_and_work_done/index.md
      - Applications of Electricity:
        - Overview: sciences/physics/applications_of_electricity/index.md

  - History:
    - Overview: history/index.md
    - America:
      - Overview: history/america/index.md
      - 1920s:
        - Overview: history/america/1920s/index.md
        - Causes of the Economic Boom: history/america/1920s/causes_of_the_boom.md
        - Henry Ford: history/america/1920s/henry_ford.md
        - Republican Policies: history/america/1920s/republican_policies.md
        - The Entertainment Industry: history/america/1920s/entertainment_industry.md
        - Life for Women in the 1920s: history/america/1920s/women.md
        - Prohibition and Organised Crime: history/america/1920s/prohibtion_and_organised_crime.md
        - How Immigrants were Treated in the 1920s: history/america/1920s/immigration.md
        - Life for African Americans in the 1920s: history/america/1920s/life_for_african_americans.md
      - The Depression:
        - Overview: history/america/the_depression/index.md
      - Post-War:
        - Overview: history/america/post_war/index.md
    - Cold War:
      - Overview: history/cold_war/index.md
      - Origins:
        - Overview: history/cold_war/origins/index.md
        - Changing Alliances: history/cold_war/origins/changing_alliances.md
        - Yalta Conference: history/cold_war/origins/yalta_conference.md
        - Potsdam Conference: history/cold_war/origins/potsdamn_conference.md
        - The Atomic Bomb: history/cold_war/origins/the_atomic_bomb.md
        - Soviet Expansion: history/cold_war/origins/soviet_expansion.md
        - Truman Doctrine and Marshall Plan: history/cold_war/origins/truman_doctrine_and_marshall_plan.md
        - Berlin Blockade and Airlift: history/cold_war/origins/berlin_blockade_and_airlift.md
      - Development:
        - Overview: history/cold_war/development/index.md
        - Communism in Asia: history/cold_war/development/communism_in_asia.md
        - NATO, Warsaw Pact, Arms Race and Space Race: history/cold_war/development/nato_warsaw_pact_arms_race_and_space_race.md
        - Khrushchev Policies: history/cold_war/development/khrushchev_policies.md
        - Hungarian Revolution: history/cold_war/development/hungary_revolution_1956.md
        - U2 Crisis: history/cold_war/development/u2_crisis.md
      - Transformation:
        - Overview: history/cold_war/transformation/index.md
        - Berlin Wall: history/cold_war/transformation/berlin_wall.md
        - Events in Cuba before 1961: history/cold_war/transformation/events_in_cuba_until_1961.md
        - Cuban Missile Crisis: history/cold_war/transformation/cuban_missile_crisis.md
        - Czechoslovakaia: history/cold_war/transformation/czechoslovakia.md
        - Detente: history/cold_war/transformation/detente.md


  - Religious Education (RE):
    - Overview: religious_education/index.md
    - Catholic Beliefs and Teaching:
      - Overview: religious_education/catholic_beliefs_and_teachings/index.md
    - Catholic Practices:
      - Overview: religious_education/catholic_practices/index.md
    - Sources of Wisdom and Authority:
      - Overview: religious_education/sources_of_wisdom_and_authority/index.md
    - Forms of Expression and Catholic Art:
      - Overview: religious_education/forms_of_expression_and_catholic_art/index.md
    - Jewish Beliefs:
      - Overview: religious_education/jewish_beliefs/index.md

  - Computing:
    - Overview: computing/index.md

  - Business:
    - Overview: business/index.md
    - Business in the Real World:
      - Overview: business/business_in_the_real_world/index.md
    - Human Resources:
      - Overview: business/human_resources/index.md
    - Marketing:
      - Overview: business/marketing/index.md