site_name: revision resources i guess
site_description: as it says
site_url: https://public-archive-sjb.github.io/revision-archive/

theme:
  name: material

  logo: assets/images/he_will_be_baked_soon.png
  favicon: assets/images/he_will_be_baked_soon.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    
    - navigation.indexes
    - navigation.tabs
    - navigation.expand
    - navigation.top

  palette:
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/lightbulb-outline
        name: lights on

    - scheme: default
      primary: black
      accent: custom
      toggle:
        icon: material/lightbulb
        name: lights off

nav:
  - Home: index.md
  - English:
    - Language: english/language/index.md
    - Literature:
      - overview: english/literature/index.md
      - paper 1:
        - Romeo & Juliet:
          - overview: english/literature/romeo_and_juliet/index.md
          - timeline: english/literature/romeo_and_juliet/timeline.md
          - trival stuff:
            - relations: english/literature/romeo_and_juliet/trivial_stuff/relations.md
            - kill feed: english/literature/romeo_and_juliet/trivial_stuff/who_kills_who.md
        - Jekyll & Hyde:
          - overview: english/literature/jekyll_and_hyde/index.md
  - Maths:
    - overview: maths/index.md
  - Sciences (Triple):
    - Biology:
      - overview: sciences/biology/index.md
    - Chemistry:
      - overview: sciences/chemistry/index.md
    - Physics:
      - overview: sciences/physics/index.md
  - History:
    - overview : history/index.md
  - Religious Education (RE):
    - overview : religious_education/index.md
  - Computing:
    - overview: computing/index.md
  - Business:
    - overview : business/index.md